# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: EuroProofNet
email:
description: >- # this means to ignore newlines until "baseurl:"
  Cost Action CA20111 [EuroProofNet](https://www.cost.eu/actions/CA20111/)
  European Research Network on Formal Proofs
# twitter_username: username
github_username: EuroProofNet
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  bio: "[COST action CA20111](https://www.cost.eu/actions/CA20111/):
**European Research Network on Formal Proofs**<br/>
[<img src=\"/assets/images/COST_LOGO_rgb_highresolution.jpg\" alt=\"COST logo\" height=\"100\">](https://www.cost.eu/)<br/>
[<img src=\"/assets/images/COST-H2020-acknowledgement-4lines.jpg\" alt=\"EU flag and COST H2020 acknowledgement\" height=\"100\">](https://ec.europa.eu/programmes/horizon2020/)<br/>
[COST](https://www.cost.eu/) (European Cooperation in Science and
Technology) is a funding agency for research and innovation
networks. Our Actions help connect research initiatives across Europe
and enable scientists to grow their ideas by sharing them with their
peers. This boosts their research, career and innovation.<br/>
<img src=\"/assets/images/zulip_icon_20.jpg\" alt=\"Zulip icon\">
[Zulip](https://epn.zulipchat.com/)"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/EuroProofNet/europroofnet.github.io"
    - label: "CA20111"
      icon: "fas fa-fw fa-link"
      url: "https://www.cost.eu/actions/CA20111/"
    - label: "COST"
      url: "https://www.cost.eu"
    - label: "H2020"
      url: "https://ec.europa.eu/programmes/horizon2020/"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/EuroProofNet/europroofnet.github.io"
    - label: "CA20111"
      icon: "fas fa-fw fa-link"
      url: "https://www.cost.eu/actions/CA20111/"
    - label: "COST"
      url: "https://www.cost.eu"

collections:
  events:
    output: true
    permalink: /:collection/:path/

defaults:
  # _events
  - scope:
      path: ""
      type: events
    values:
      layout: single
      author_profile: true
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
